model_list:

  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY1
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY2
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY3
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY4
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY5
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY6
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY7
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY8
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY9
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY10
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY11
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY12
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY13
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY14
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY15
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY15
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY16
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY17
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY18
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY19
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY20
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY21
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY22
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY23
  - model_name: gemini-lite
    litellm_params:
      model: gemini-flash-lite-latest
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY24

      
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY1
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY2
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY3
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY4
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY5
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY6
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY7
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY8
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY9
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY10
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY11
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY12
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY13
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY14
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY15
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY16
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY17
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY18
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY19
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY20
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY21
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY22
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY23
  - model_name: gemini-flash
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/GEMINI_API_KEY24


  - model_name: QWEN-3    
    litellm_params:
      model: chutes/Qwen/Qwen3-32B-TEE
      api_key: os.environ/CHUTES_API_KEY
      allowed_openai_params: ["tools", "tool_choice"] 

  - model_name: QWEN-3.5    
    litellm_params:
      model: chutes/Qwen/Qwen3.5-397B-A17B-TEE
      api_key: os.environ/CHUTES_API_KEY
      allowed_openai_params: ["tools", "tool_choice"] 

  - model_name: KIMI-K-3   
    litellm_params:
      model: chutes/moonshotai/Kimi-K3-TEE
      api_key: os.environ/CHUTES_API_KEY

  - model_name: GLM-5.2   
    litellm_params:
      model: chutes/zai-org/GLM-5.2-TEE
      api_key: os.environ/CHUTES_API_KEY
      allowed_openai_params: ["tools", "tool_choice"] 

  - model_name: MiniMax   
    litellm_params:
      model: chutes/MiniMaxAI/MiniMax-M2.5-TEE
      api_key: os.environ/CHUTES_API_KEY
      allowed_openai_params: ["tools", "tool_choice"] 

  - model_name: DeepSeek   
    litellm_params:
      model: chutes/deepseek-ai/DeepSeek-V3.2-TEE
      api_key: os.environ/CHUTES_API_KEY
      allowed_openai_params: ["tools", "tool_choice"]   

  - model_name: gemini-xcycle
    litellm_params:
      model: gemini-3.6-flash
      custom_llm_provider: gemini
      api_key: os.environ/XCYCLE_KEY

router_settings:
  routing_strategy: round-robin  
  num_retries: 5                             
  cooldown_time: 86400                       
  allowed_fails: 1

general_settings:
  master_key: "LlnrmvdUt201X3Zwd8BTG2pdDY5044eCgqv8M7DC"

litellm_settings:
  telemetry: False
  set_verbose: False